package com.zxb.ownmallmapper.mapper;

import com.zxb.ownmallmapper.pojo.Sysinfo;
import java.util.List;

public interface SysinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String nodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated
     */
    int insert(Sysinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated
     */
    Sysinfo selectByPrimaryKey(String nodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated
     */
    List<Sysinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sysinfo record);
}