package com.zxb.ownmallmapper.mapper;

import com.zxb.ownmallmapper.pojo.UmsAdmin;
import java.util.List;

public interface UmsAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbggenerated
     */
    int insert(UmsAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbggenerated
     */
    UmsAdmin selectByPrimaryKey(String adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbggenerated
     */
    List<UmsAdmin> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UmsAdmin record);
}