package com.zxb.ownmallmapper.mapper;

import com.zxb.ownmallmapper.pojo.UmsMenu;
import java.util.List;

public interface UmsMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_menu
     *
     * @mbggenerated
     */
    int insert(UmsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_menu
     *
     * @mbggenerated
     */
    UmsMenu selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_menu
     *
     * @mbggenerated
     */
    List<UmsMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UmsMenu record);
}