package com.zxb.ownmallmapper.mapper;

import com.zxb.ownmallmapper.pojo.UmsPermissionMenu;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsPermissionMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("permissionId") String permissionId, @Param("menuId") String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission_menu
     *
     * @mbggenerated
     */
    int insert(UmsPermissionMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission_menu
     *
     * @mbggenerated
     */
    List<UmsPermissionMenu> selectAll();
}