package com.zxb.ownmallmapper.mapper;

import com.zxb.ownmallmapper.pojo.UmsRole;
import java.util.List;

public interface UmsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbggenerated
     */
    int insert(UmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbggenerated
     */
    List<UmsRole> selectAll();

    /**
     * 在当前的系统删除角色
     * @param umsRole
     * @return
     */
    int deleteRoleOfThisSys(UmsRole umsRole);

    /**
     * 更新角色信息
     * @param umsRole
     * @return
     */
    int updateByRoleId(UmsRole umsRole);
}