package com.zxb.ownmallmapper.mapper;

import com.zxb.ownmallmapper.pojo.UmsRolePermission;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("roleId") String roleId, @Param("permissionId") String permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_permission
     *
     * @mbggenerated
     */
    int insert(UmsRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_permission
     *
     * @mbggenerated
     */
    List<UmsRolePermission> selectAll();

    /**
     * 查询所有该角色的数据
     * @param UmsRolePermission
     * @return
     */
    long selCountsByRoleId(UmsRolePermission UmsRolePermission);

    /**
     * 根据roleId删除数据
     * @param umsRolePermission
     * @return
     */
    int deleteByRoleId(UmsRolePermission umsRolePermission);


}