package com.zxb.ownmallmapper.mapper;

import com.zxb.ownmallmapper.pojo.UmsRole;
import java.util.List;

public interface UmsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbggenerated
     */
    int insert(UmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbggenerated
     */
    List<UmsRole> selectAll();
}