package com.zxb.ownmallmapper.mapper;

import com.zxb.ownmallmapper.pojo.UmsRoleGroupRole;
import java.util.List;

public interface UmsRoleGroupRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_group_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String rgrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_group_role
     *
     * @mbggenerated
     */
    int insert(UmsRoleGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_group_role
     *
     * @mbggenerated
     */
    UmsRoleGroupRole selectByPrimaryKey(String rgrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_group_role
     *
     * @mbggenerated
     */
    List<UmsRoleGroupRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_group_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UmsRoleGroupRole record);
}