package com.zxb.ownmallmapper.mapper;

import com.zxb.ownmallmapper.pojo.UmsRoleGroup;
import java.util.List;

public interface UmsRoleGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_group
     *
     * @mbggenerated
     */
    int insert(UmsRoleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_group
     *
     * @mbggenerated
     */
    UmsRoleGroup selectByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_group
     *
     * @mbggenerated
     */
    List<UmsRoleGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UmsRoleGroup record);
}