package com.zxb.ownmallmapper.mapper;

import com.zxb.ownmallmapper.pojo.UmsRolePermission;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("roleId") String roleId, @Param("permissionId") String permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_permission
     *
     * @mbggenerated
     */
    int insert(UmsRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_permission
     *
     * @mbggenerated
     */
    List<UmsRolePermission> selectAll();
}