package com.zxb.ownmallmapper.pojo;

import java.io.Serializable;

public class Sysinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.node_id
     *
     * @mbggenerated
     */
    private String nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_no
     *
     * @mbggenerated
     */
    private String sysNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_password
     *
     * @mbggenerated
     */
    private String sysPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_name
     *
     * @mbggenerated
     */
    private String sysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_nick
     *
     * @mbggenerated
     */
    private String sysNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_engnish_name
     *
     * @mbggenerated
     */
    private String sysEngnishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_engnish_nick
     *
     * @mbggenerated
     */
    private String sysEngnishNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_access_domains
     *
     * @mbggenerated
     */
    private String sysAccessDomains;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_access_token_timeout
     *
     * @mbggenerated
     */
    private String sysAccessTokenTimeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_refresh_token_timeout
     *
     * @mbggenerated
     */
    private String sysRefreshTokenTimeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_show_flag
     *
     * @mbggenerated
     */
    private String sysShowFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_authentication_method
     *
     * @mbggenerated
     */
    private String sysAuthenticationMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_server_address
     *
     * @mbggenerated
     */
    private String sysServerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_server_port
     *
     * @mbggenerated
     */
    private String sysServerPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_create_people_id
     *
     * @mbggenerated
     */
    private String sysCreatePeopleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_create_people_type
     *
     * @mbggenerated
     */
    private String sysCreatePeopleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_create_time
     *
     * @mbggenerated
     */
    private String sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sys_updata_time
     *
     * @mbggenerated
     */
    private String sysUpdataTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sysinfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.node_id
     *
     * @return the value of sysinfo.node_id
     *
     * @mbggenerated
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.node_id
     *
     * @param nodeId the value for sysinfo.node_id
     *
     * @mbggenerated
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_no
     *
     * @return the value of sysinfo.sys_no
     *
     * @mbggenerated
     */
    public String getSysNo() {
        return sysNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_no
     *
     * @param sysNo the value for sysinfo.sys_no
     *
     * @mbggenerated
     */
    public void setSysNo(String sysNo) {
        this.sysNo = sysNo == null ? null : sysNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_password
     *
     * @return the value of sysinfo.sys_password
     *
     * @mbggenerated
     */
    public String getSysPassword() {
        return sysPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_password
     *
     * @param sysPassword the value for sysinfo.sys_password
     *
     * @mbggenerated
     */
    public void setSysPassword(String sysPassword) {
        this.sysPassword = sysPassword == null ? null : sysPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_name
     *
     * @return the value of sysinfo.sys_name
     *
     * @mbggenerated
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_name
     *
     * @param sysName the value for sysinfo.sys_name
     *
     * @mbggenerated
     */
    public void setSysName(String sysName) {
        this.sysName = sysName == null ? null : sysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_nick
     *
     * @return the value of sysinfo.sys_nick
     *
     * @mbggenerated
     */
    public String getSysNick() {
        return sysNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_nick
     *
     * @param sysNick the value for sysinfo.sys_nick
     *
     * @mbggenerated
     */
    public void setSysNick(String sysNick) {
        this.sysNick = sysNick == null ? null : sysNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_engnish_name
     *
     * @return the value of sysinfo.sys_engnish_name
     *
     * @mbggenerated
     */
    public String getSysEngnishName() {
        return sysEngnishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_engnish_name
     *
     * @param sysEngnishName the value for sysinfo.sys_engnish_name
     *
     * @mbggenerated
     */
    public void setSysEngnishName(String sysEngnishName) {
        this.sysEngnishName = sysEngnishName == null ? null : sysEngnishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_engnish_nick
     *
     * @return the value of sysinfo.sys_engnish_nick
     *
     * @mbggenerated
     */
    public String getSysEngnishNick() {
        return sysEngnishNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_engnish_nick
     *
     * @param sysEngnishNick the value for sysinfo.sys_engnish_nick
     *
     * @mbggenerated
     */
    public void setSysEngnishNick(String sysEngnishNick) {
        this.sysEngnishNick = sysEngnishNick == null ? null : sysEngnishNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_access_domains
     *
     * @return the value of sysinfo.sys_access_domains
     *
     * @mbggenerated
     */
    public String getSysAccessDomains() {
        return sysAccessDomains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_access_domains
     *
     * @param sysAccessDomains the value for sysinfo.sys_access_domains
     *
     * @mbggenerated
     */
    public void setSysAccessDomains(String sysAccessDomains) {
        this.sysAccessDomains = sysAccessDomains == null ? null : sysAccessDomains.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_access_token_timeout
     *
     * @return the value of sysinfo.sys_access_token_timeout
     *
     * @mbggenerated
     */
    public String getSysAccessTokenTimeout() {
        return sysAccessTokenTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_access_token_timeout
     *
     * @param sysAccessTokenTimeout the value for sysinfo.sys_access_token_timeout
     *
     * @mbggenerated
     */
    public void setSysAccessTokenTimeout(String sysAccessTokenTimeout) {
        this.sysAccessTokenTimeout = sysAccessTokenTimeout == null ? null : sysAccessTokenTimeout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_refresh_token_timeout
     *
     * @return the value of sysinfo.sys_refresh_token_timeout
     *
     * @mbggenerated
     */
    public String getSysRefreshTokenTimeout() {
        return sysRefreshTokenTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_refresh_token_timeout
     *
     * @param sysRefreshTokenTimeout the value for sysinfo.sys_refresh_token_timeout
     *
     * @mbggenerated
     */
    public void setSysRefreshTokenTimeout(String sysRefreshTokenTimeout) {
        this.sysRefreshTokenTimeout = sysRefreshTokenTimeout == null ? null : sysRefreshTokenTimeout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_show_flag
     *
     * @return the value of sysinfo.sys_show_flag
     *
     * @mbggenerated
     */
    public String getSysShowFlag() {
        return sysShowFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_show_flag
     *
     * @param sysShowFlag the value for sysinfo.sys_show_flag
     *
     * @mbggenerated
     */
    public void setSysShowFlag(String sysShowFlag) {
        this.sysShowFlag = sysShowFlag == null ? null : sysShowFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_authentication_method
     *
     * @return the value of sysinfo.sys_authentication_method
     *
     * @mbggenerated
     */
    public String getSysAuthenticationMethod() {
        return sysAuthenticationMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_authentication_method
     *
     * @param sysAuthenticationMethod the value for sysinfo.sys_authentication_method
     *
     * @mbggenerated
     */
    public void setSysAuthenticationMethod(String sysAuthenticationMethod) {
        this.sysAuthenticationMethod = sysAuthenticationMethod == null ? null : sysAuthenticationMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_server_address
     *
     * @return the value of sysinfo.sys_server_address
     *
     * @mbggenerated
     */
    public String getSysServerAddress() {
        return sysServerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_server_address
     *
     * @param sysServerAddress the value for sysinfo.sys_server_address
     *
     * @mbggenerated
     */
    public void setSysServerAddress(String sysServerAddress) {
        this.sysServerAddress = sysServerAddress == null ? null : sysServerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_server_port
     *
     * @return the value of sysinfo.sys_server_port
     *
     * @mbggenerated
     */
    public String getSysServerPort() {
        return sysServerPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_server_port
     *
     * @param sysServerPort the value for sysinfo.sys_server_port
     *
     * @mbggenerated
     */
    public void setSysServerPort(String sysServerPort) {
        this.sysServerPort = sysServerPort == null ? null : sysServerPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_create_people_id
     *
     * @return the value of sysinfo.sys_create_people_id
     *
     * @mbggenerated
     */
    public String getSysCreatePeopleId() {
        return sysCreatePeopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_create_people_id
     *
     * @param sysCreatePeopleId the value for sysinfo.sys_create_people_id
     *
     * @mbggenerated
     */
    public void setSysCreatePeopleId(String sysCreatePeopleId) {
        this.sysCreatePeopleId = sysCreatePeopleId == null ? null : sysCreatePeopleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_create_people_type
     *
     * @return the value of sysinfo.sys_create_people_type
     *
     * @mbggenerated
     */
    public String getSysCreatePeopleType() {
        return sysCreatePeopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_create_people_type
     *
     * @param sysCreatePeopleType the value for sysinfo.sys_create_people_type
     *
     * @mbggenerated
     */
    public void setSysCreatePeopleType(String sysCreatePeopleType) {
        this.sysCreatePeopleType = sysCreatePeopleType == null ? null : sysCreatePeopleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_create_time
     *
     * @return the value of sysinfo.sys_create_time
     *
     * @mbggenerated
     */
    public String getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_create_time
     *
     * @param sysCreateTime the value for sysinfo.sys_create_time
     *
     * @mbggenerated
     */
    public void setSysCreateTime(String sysCreateTime) {
        this.sysCreateTime = sysCreateTime == null ? null : sysCreateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sys_updata_time
     *
     * @return the value of sysinfo.sys_updata_time
     *
     * @mbggenerated
     */
    public String getSysUpdataTime() {
        return sysUpdataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sys_updata_time
     *
     * @param sysUpdataTime the value for sysinfo.sys_updata_time
     *
     * @mbggenerated
     */
    public void setSysUpdataTime(String sysUpdataTime) {
        this.sysUpdataTime = sysUpdataTime == null ? null : sysUpdataTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.parent_id
     *
     * @return the value of sysinfo.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.parent_id
     *
     * @param parentId the value for sysinfo.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nodeId=").append(nodeId);
        sb.append(", sysNo=").append(sysNo);
        sb.append(", sysPassword=").append(sysPassword);
        sb.append(", sysName=").append(sysName);
        sb.append(", sysNick=").append(sysNick);
        sb.append(", sysEngnishName=").append(sysEngnishName);
        sb.append(", sysEngnishNick=").append(sysEngnishNick);
        sb.append(", sysAccessDomains=").append(sysAccessDomains);
        sb.append(", sysAccessTokenTimeout=").append(sysAccessTokenTimeout);
        sb.append(", sysRefreshTokenTimeout=").append(sysRefreshTokenTimeout);
        sb.append(", sysShowFlag=").append(sysShowFlag);
        sb.append(", sysAuthenticationMethod=").append(sysAuthenticationMethod);
        sb.append(", sysServerAddress=").append(sysServerAddress);
        sb.append(", sysServerPort=").append(sysServerPort);
        sb.append(", sysCreatePeopleId=").append(sysCreatePeopleId);
        sb.append(", sysCreatePeopleType=").append(sysCreatePeopleType);
        sb.append(", sysCreateTime=").append(sysCreateTime);
        sb.append(", sysUpdataTime=").append(sysUpdataTime);
        sb.append(", parentId=").append(parentId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}